apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: shubham-ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service

        image: shubham5799/product-service:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 5000